services:
  database:
    image: postgres:18
    container_name: postgres-db-TKC
    environment:
      - POSTGRES_DB=mi_tp2_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./db/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata:
