// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createPago = `-- name: CreatePago :one

INSERT INTO pago (
    id_suscripcion
, monto, fecha_pago
) VALUES (
    $1, $2, $3
)
RETURNING id_pago, id_suscripcion, monto, fecha_pago, created_at
`

type CreatePagoParams struct {
	IDSuscripcion int32     `json:"id_suscripcion"`
	Monto         string    `json:"monto"`
	FechaPago     time.Time `json:"fecha_pago"`
}

// consultas  de pago
func (q *Queries) CreatePago(ctx context.Context, arg CreatePagoParams) (Pago, error) {
	row := q.db.QueryRowContext(ctx, createPago, arg.IDSuscripcion, arg.Monto, arg.FechaPago)
	var i Pago
	err := row.Scan(
		&i.IDPago,
		&i.IDSuscripcion,
		&i.Monto,
		&i.FechaPago,
		&i.CreatedAt,
	)
	return i, err
}

const createServicio = `-- name: CreateServicio :one

INSERT INTO servicio (
    nombre, categoria
) VALUES (
    $1, $2
)
RETURNING id_servicio, nombre, categoria, created_at
`

type CreateServicioParams struct {
	Nombre    string `json:"nombre"`
	Categoria string `json:"categoria"`
}

// consultas del servicio
func (q *Queries) CreateServicio(ctx context.Context, arg CreateServicioParams) (Servicio, error) {
	row := q.db.QueryRowContext(ctx, createServicio, arg.Nombre, arg.Categoria)
	var i Servicio
	err := row.Scan(
		&i.IDServicio,
		&i.Nombre,
		&i.Categoria,
		&i.CreatedAt,
	)
	return i, err
}

const createSubscripcion = `-- name: CreateSubscripcion :one

INSERT INTO suscripcion (
    id_usuario, id_servicio, monto, fecha_vencimiento, fecha_inicio, usuario_cuenta, password_cuenta, estado
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id_suscripcion, id_usuario, id_servicio, monto, fecha_vencimiento, fecha_inicio, usuario_cuenta, password_cuenta, estado, created_at
`

type CreateSubscripcionParams struct {
	IDUsuario        int32          `json:"id_usuario"`
	IDServicio       int32          `json:"id_servicio"`
	Monto            string         `json:"monto"`
	FechaVencimiento time.Time      `json:"fecha_vencimiento"`
	FechaInicio      time.Time      `json:"fecha_inicio"`
	UsuarioCuenta    string         `json:"usuario_cuenta"`
	PasswordCuenta   string         `json:"password_cuenta"`
	Estado           sql.NullString `json:"estado"`
}

// consulta para suscripcion
func (q *Queries) CreateSubscripcion(ctx context.Context, arg CreateSubscripcionParams) (Suscripcion, error) {
	row := q.db.QueryRowContext(ctx, createSubscripcion,
		arg.IDUsuario,
		arg.IDServicio,
		arg.Monto,
		arg.FechaVencimiento,
		arg.FechaInicio,
		arg.UsuarioCuenta,
		arg.PasswordCuenta,
		arg.Estado,
	)
	var i Suscripcion
	err := row.Scan(
		&i.IDSuscripcion,
		&i.IDUsuario,
		&i.IDServicio,
		&i.Monto,
		&i.FechaVencimiento,
		&i.FechaInicio,
		&i.UsuarioCuenta,
		&i.PasswordCuenta,
		&i.Estado,
		&i.CreatedAt,
	)
	return i, err
}

const createUsuario = `-- name: CreateUsuario :one

INSERT INTO usuario (
    nombre, apellido, dni, email, password
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id_usuario, nombre, apellido, dni, email, password, created_at
`

type CreateUsuarioParams struct {
	Nombre   string `json:"nombre"`
	Apellido string `json:"apellido"`
	Dni      string `json:"dni"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

// consultas para el usuario
func (q *Queries) CreateUsuario(ctx context.Context, arg CreateUsuarioParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, createUsuario,
		arg.Nombre,
		arg.Apellido,
		arg.Dni,
		arg.Email,
		arg.Password,
	)
	var i Usuario
	err := row.Scan(
		&i.IDUsuario,
		&i.Nombre,
		&i.Apellido,
		&i.Dni,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const deletePago = `-- name: DeletePago :exec
DELETE FROM pago 
WHERE id_pago = $1
`

func (q *Queries) DeletePago(ctx context.Context, idPago int32) error {
	_, err := q.db.ExecContext(ctx, deletePago, idPago)
	return err
}

const deleteServicio = `-- name: DeleteServicio :exec
DELETE FROM servicio 
WHERE id_servicio = $1
`

func (q *Queries) DeleteServicio(ctx context.Context, idServicio int32) error {
	_, err := q.db.ExecContext(ctx, deleteServicio, idServicio)
	return err
}

const deleteSubscripcion = `-- name: DeleteSubscripcion :exec
DELETE FROM suscripcion 
WHERE id_suscripcion = $1
`

func (q *Queries) DeleteSubscripcion(ctx context.Context, idSuscripcion int32) error {
	_, err := q.db.ExecContext(ctx, deleteSubscripcion, idSuscripcion)
	return err
}

const deleteUsuario = `-- name: DeleteUsuario :exec
DELETE FROM usuario 
WHERE id_usuario = $1
`

func (q *Queries) DeleteUsuario(ctx context.Context, idUsuario int32) error {
	_, err := q.db.ExecContext(ctx, deleteUsuario, idUsuario)
	return err
}

const getPago = `-- name: GetPago :one
SELECT id_pago, id_suscripcion, monto, fecha_pago, created_at FROM pago 
WHERE id_pago = $1
`

func (q *Queries) GetPago(ctx context.Context, idPago int32) (Pago, error) {
	row := q.db.QueryRowContext(ctx, getPago, idPago)
	var i Pago
	err := row.Scan(
		&i.IDPago,
		&i.IDSuscripcion,
		&i.Monto,
		&i.FechaPago,
		&i.CreatedAt,
	)
	return i, err
}

const getServicio = `-- name: GetServicio :one
SELECT id_servicio, nombre, categoria, created_at FROM servicio 
WHERE id_servicio = $1
`

func (q *Queries) GetServicio(ctx context.Context, idServicio int32) (Servicio, error) {
	row := q.db.QueryRowContext(ctx, getServicio, idServicio)
	var i Servicio
	err := row.Scan(
		&i.IDServicio,
		&i.Nombre,
		&i.Categoria,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscripcion = `-- name: GetSubscripcion :one
SELECT id_suscripcion, id_usuario, id_servicio, monto, fecha_vencimiento, fecha_inicio, usuario_cuenta, password_cuenta, estado, created_at FROM suscripcion 
WHERE id_suscripcion = $1
`

func (q *Queries) GetSubscripcion(ctx context.Context, idSuscripcion int32) (Suscripcion, error) {
	row := q.db.QueryRowContext(ctx, getSubscripcion, idSuscripcion)
	var i Suscripcion
	err := row.Scan(
		&i.IDSuscripcion,
		&i.IDUsuario,
		&i.IDServicio,
		&i.Monto,
		&i.FechaVencimiento,
		&i.FechaInicio,
		&i.UsuarioCuenta,
		&i.PasswordCuenta,
		&i.Estado,
		&i.CreatedAt,
	)
	return i, err
}

const getUsuario = `-- name: GetUsuario :one
SELECT id_usuario, nombre, apellido, dni, email, password, created_at FROM usuario 
WHERE id_usuario = $1
`

func (q *Queries) GetUsuario(ctx context.Context, idUsuario int32) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUsuario, idUsuario)
	var i Usuario
	err := row.Scan(
		&i.IDUsuario,
		&i.Nombre,
		&i.Apellido,
		&i.Dni,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const listPagos = `-- name: ListPagos :many
SELECT id_pago, id_suscripcion, monto, fecha_pago, created_at FROM pago 
WHERE id_suscripcion = $1 
ORDER BY fecha_pago DESC
`

func (q *Queries) ListPagos(ctx context.Context, idSuscripcion int32) ([]Pago, error) {
	rows, err := q.db.QueryContext(ctx, listPagos, idSuscripcion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pago
	for rows.Next() {
		var i Pago
		if err := rows.Scan(
			&i.IDPago,
			&i.IDSuscripcion,
			&i.Monto,
			&i.FechaPago,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicios = `-- name: ListServicios :many
SELECT id_servicio, nombre, categoria, created_at FROM servicio 
ORDER BY nombre
`

func (q *Queries) ListServicios(ctx context.Context) ([]Servicio, error) {
	rows, err := q.db.QueryContext(ctx, listServicios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Servicio
	for rows.Next() {
		var i Servicio
		if err := rows.Scan(
			&i.IDServicio,
			&i.Nombre,
			&i.Categoria,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuscripcionesUsuario = `-- name: ListSuscripcionesUsuario :many
SELECT 
    sub.id_suscripcion
,
    sub.monto,
    sub.fecha_vencimiento,
    sub.fecha_inicio,
    sub.usuario_cuenta,
    sub.estado,
    ser.nombre AS servicio_nombre,
    ser.categoria AS servicio_categoria
FROM suscripcion sub
JOIN servicio ser ON sub.id_servicio = ser.id_servicio
WHERE sub.id_usuario = $1
ORDER BY ser.nombre ASC
`

type ListSuscripcionesUsuarioRow struct {
	IDSuscripcion     int32          `json:"id_suscripcion"`
	Monto             string         `json:"monto"`
	FechaVencimiento  time.Time      `json:"fecha_vencimiento"`
	FechaInicio       time.Time      `json:"fecha_inicio"`
	UsuarioCuenta     string         `json:"usuario_cuenta"`
	Estado            sql.NullString `json:"estado"`
	ServicioNombre    string         `json:"servicio_nombre"`
	ServicioCategoria string         `json:"servicio_categoria"`
}

func (q *Queries) ListSuscripcionesUsuario(ctx context.Context, idUsuario int32) ([]ListSuscripcionesUsuarioRow, error) {
	rows, err := q.db.QueryContext(ctx, listSuscripcionesUsuario, idUsuario)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSuscripcionesUsuarioRow
	for rows.Next() {
		var i ListSuscripcionesUsuarioRow
		if err := rows.Scan(
			&i.IDSuscripcion,
			&i.Monto,
			&i.FechaVencimiento,
			&i.FechaInicio,
			&i.UsuarioCuenta,
			&i.Estado,
			&i.ServicioNombre,
			&i.ServicioCategoria,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsuarios = `-- name: ListUsuarios :many
SELECT id_usuario, nombre, apellido, dni, email, password, created_at FROM usuario 
ORDER BY apellido, nombre
`

func (q *Queries) ListUsuarios(ctx context.Context) ([]Usuario, error) {
	rows, err := q.db.QueryContext(ctx, listUsuarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.IDUsuario,
			&i.Nombre,
			&i.Apellido,
			&i.Dni,
			&i.Email,
			&i.Password,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServicio = `-- name: UpdateServicio :exec
UPDATE servicio 
SET nombre = $2, 
    categoria = $3
WHERE id_servicio = $1
`

type UpdateServicioParams struct {
	IDServicio int32  `json:"id_servicio"`
	Nombre     string `json:"nombre"`
	Categoria  string `json:"categoria"`
}

func (q *Queries) UpdateServicio(ctx context.Context, arg UpdateServicioParams) error {
	_, err := q.db.ExecContext(ctx, updateServicio, arg.IDServicio, arg.Nombre, arg.Categoria)
	return err
}

const updateSubscripcion = `-- name: UpdateSubscripcion :exec
UPDATE suscripcion 
SET monto = $2, 
    fecha_vencimiento = $3, 
    estado = $4, 
    usuario_cuenta = $5, 
    password_cuenta = $6
WHERE id_suscripcion = $1
`

type UpdateSubscripcionParams struct {
	IDSuscripcion    int32          `json:"id_suscripcion"`
	Monto            string         `json:"monto"`
	FechaVencimiento time.Time      `json:"fecha_vencimiento"`
	Estado           sql.NullString `json:"estado"`
	UsuarioCuenta    string         `json:"usuario_cuenta"`
	PasswordCuenta   string         `json:"password_cuenta"`
}

func (q *Queries) UpdateSubscripcion(ctx context.Context, arg UpdateSubscripcionParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscripcion,
		arg.IDSuscripcion,
		arg.Monto,
		arg.FechaVencimiento,
		arg.Estado,
		arg.UsuarioCuenta,
		arg.PasswordCuenta,
	)
	return err
}

const updateUsuario = `-- name: UpdateUsuario :exec
UPDATE usuario 
SET nombre = $2, 
    apellido = $3, 
    dni = $4, 
    email = $5, 
    password = $6
WHERE id_usuario = $1
`

type UpdateUsuarioParams struct {
	IDUsuario int32  `json:"id_usuario"`
	Nombre    string `json:"nombre"`
	Apellido  string `json:"apellido"`
	Dni       string `json:"dni"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

func (q *Queries) UpdateUsuario(ctx context.Context, arg UpdateUsuarioParams) error {
	_, err := q.db.ExecContext(ctx, updateUsuario,
		arg.IDUsuario,
		arg.Nombre,
		arg.Apellido,
		arg.Dni,
		arg.Email,
		arg.Password,
	)
	return err
}
